### ISSUE TITLE
Recessive node attributes not set anymore in Xpp3DomUtils when dominant root node value is empty

### ISSUE THREAD

**Issue by guylabs** [codehaus-plexus/plexus-utils#230] opened 2023-01-05 21:58 UTC
The change in https://github.com/codehaus-plexus/plexus-utils/commit/67ac243dbc6434c03a9b1582d94aef6bf2b5cf95 causes different merging outcomes before and after the change. This has been discussed in https://github.com/codehaus-plexus/plexus-utils/commit/67ac243dbc6434c03a9b1582d94aef6bf2b5cf95#r94996401.

A reproducer of the issue is shown in https://github.com/guylabs/plexus-utils-merge-xml-reproducer where the same configuration is executed on Maven `3.8.7` and on Maven `4.0.0-alpha3`.

**Comment by guylabs** [comment] 2023-01-09 19:55
@kwin were you able to have a look at the reproducer already?

**Comment by guylabs** [comment] 2023-01-09 20:06
It's this part that has been removed:

https://github.com/codehaus-plexus/plexus-utils/commit/67ac243dbc6434c03a9b1582d94aef6bf2b5cf95#diff-8daf65446126b8abe5b619665bb0697d522273192ee8cb2bd74a371e3eb3b407L143-L148

It's not easy to simplify but the reproducer shows nicely the diff between the files and what is not working as expected.

**Comment by guylabs** [comment] 2023-01-17 21:31
@kwin any update on this?

**Comment by c00ler** [comment] 2023-02-06 14:34
@kwin @guylabs I wrote a simple reproducer test for this issue: https://github.com/c00ler/plexus-utils-merge-xml-reproducer/blob/main/src/test/java/com/github/avenderov/ReproducerTest.java. It shows that the issue is **not** in the `plexus-utils`. I run the test with the version before the change `3.4.2` and after the change `3.5.0`, and in both cases test passes. The issue is happening in `Maven 4` as it's not using `Xpp3Dom` class and corresponding utility methods anymore but has its own implementation that has a regression. I will create an issue in the maven issue tracker.

**Comment by c00ler** [comment] 2023-02-06 15:53
The corresponding ticket in the maven issue tracker: https://issues.apache.org/jira/browse/MNG-7683

**Comment by gnodet** [comment] 2023-03-01 16:49
Closing as the issue lies in the maven 4 code base.

**Closed by gnodet** 2023-03-01 16:49 UTC
